spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.116.6.235:3306/blog?serverTimezone=GMT&characterEncoding=utf-8
    password: mysqlXYC@1996
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 127.0.0.1
logging:
  level:
    root: warn
    com.xyc: info
  file: log/blog-pro.log
server:
  port: 8100

