spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/butterfly-blog?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: 1996
    username: root
  redis:
    port: 6379
   # host: 47.102.130.142
    host: 127.0.0.1
  application:
    name: butterfly-blog
  main:
    web-application-type: reactive
logging:
  level:
    root: info
    com.xyc: debug
  file:
    name: log/blog-dev.log
server:
  port: 8100
  #设置编码问题

eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: false

#导入日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl